// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6EsN8-eZuT0qPAYnfOdajDFVh5SLHgeU',
    appId: '1:792934965462:android:377a39482a8f16649a2977',
    messagingSenderId: '792934965462',
    projectId: 'unity4-academy',
    storageBucket: 'unity4-academy.firebasestorage.app',
  );
  
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMzuFiUnggbbK_uQMPR8tIahrv3UVNv7U',
    appId: '1:792934965462:ios:e127916ebf8e32d59a2977',
    messagingSenderId: '792934965462',
    projectId: 'unity4-academy',
    storageBucket: 'unity4-academy.firebasestorage.app',
    iosBundleId: 'com.example.unity4Academy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMzuFiUnggbbK_uQMPR8tIahrv3UVNv7U',
    appId: '1:792934965462:ios:e127916ebf8e32d59a2977',
    messagingSenderId: '792934965462',
    projectId: 'unity4-academy',
    storageBucket: 'unity4-academy.firebasestorage.app',
    iosBundleId: 'com.example.unity4Academy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfLaiUHZaFdP46AcsqnMb9WJN3SYUGEEU',
    appId: '1:792934965462:web:cfc8056223b64aa79a2977',
    messagingSenderId: '792934965462',
    projectId: 'unity4-academy',
    authDomain: 'unity4-academy.firebaseapp.com',
    storageBucket: 'unity4-academy.firebasestorage.app',
    measurementId: 'G-HKM5M1Y9WL',
  );

}